# Generated by Django 5.2 on 2025-04-03 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_genre_remove_comments_blog_remove_comments_user_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN must be either 10 or 13 digits long.', regex='^\\d{10}|\\d{13}$')]),
        ),
    ]
